In [1]:
import pandas as pd
import yfinance as yf
from datetime import datetime
from tqdm import tqdm

In [12]:
start_date = datetime(2021, 1, 1)
end_date = datetime(2024, 11, 15)

In [79]:
stock_list = [
   "BACQU", "NTWOU", "GSRTU", "ADUR", "WLACU", "ASPCU", "ACOG", "IZTC", "FBLA", "WRD"
]

In [80]:
percentage_changes = pd.DataFrame()

for equity_name in tqdm(stock_list, desc="Downloading data"):
    equity_data = yf.download(equity_name, start=start_date, end=end_date)
    pct_change = equity_data['Adj Close'].pct_change().dropna()
    print(pct_change[0:1])
    percentage_changes[equity_name] = pct_change

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACOG']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2021-01-01 00:00:00 -> 2024-11-15 00:00:00)')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['IZTC']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2021-01-01 00:00:00 -> 2024-11-15 00:00:00)')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Downloading data: 100%|██████████| 10/10 [00:00<00:00, 55.71it/s]

Ticker                        BACQU
Date
2024-11-04 00:00:00+00:00 -0.000501
Ticker                     NTWOU
Date
2024-11-04 00:00:00+00:00    0.0
Ticker                        GSRTU
Date
2024-11-08 00:00:00+00:00 -0.001001
Ticker                         ADUR
Date
2024-08-16 00:00:00+00:00  0.029197
Ticker                     WLACU
Date
2024-11-11 00:00:00+00:00    0.0
Ticker                     ASPCU
Date
2024-11-11 00:00:00+00:00    0.0
Empty DataFrame
Columns: [ACOG]
Index: []
Empty DataFrame
Columns: [IZTC]
Index: []
Ticker                         FBLA
Date
2024-10-24 00:00:00+00:00 -0.013491
Ticker                         WRD
Date
2024-10-28 00:00:00+00:00  0.02719

In [81]:
correlation_matrix = percentage_changes.corr()
display(correlation_matrix)

,BACQU,NTWOU,GSRTU,ADUR,WLACU,ASPCU,ACOG,IZTC,FBLA,WRD
BACQU,1.000000,0.623066,0.216217,0.355245,-0.379827,0.967361,NaN,NaN,0.053742,-0.026347
NTWOU,0.623066,1.000000,-0.346366,-0.211766,0.705787,0.046425,NaN,NaN,0.143256,-0.479195
GSRTU,0.216217,-0.346366,1.000000,0.176286,-0.577350,-0.342405,NaN,NaN,0.123126,0.741246
ADUR,0.355245,-0.211766,0.176286,1.000000,-0.365897,0.938876,NaN,NaN,-0.394053,0.020708
WLACU,-0.379827,0.705787,-0.577350,-0.365897,1.000000,-0.569344,NaN,NaN,0.211001,-0.890991
ASPCU,0.967361,0.046425,-0.342405,0.938876,-0.569344,1.000000,NaN,NaN,-0.565145,0.141902
ACOG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IZTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FBLA,0.053742,0.143256,0.123126,-0.394053,0.211001,-0.565145,NaN,NaN,1.000000,-0.048383
WRD,-0.026347,-0.479195,0.741246,0.020708,-0.890991,0.141902,NaN,NaN,-0.048383,1.000000